# Generated by Django 6.0.3 on 2026-04-01 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ponto', models.CharField(max_length=50, unique=True)),
                ('nome_cadastrador', models.CharField(max_length=150)),
                ('data_cadastro', models.DateField()),
                ('hora_cadastro', models.TimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status_sincronizacao', models.CharField(default='pendente', max_length=30)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_interno', models.CharField(max_length=100, unique=True)),
                ('rotulo', models.CharField(max_length=150)),
                ('tipo_campo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('lista', 'Lista Suspensa'), ('data', 'Data'), ('hora', 'Hora'), ('booleano', 'Sim/Não'), ('textarea', 'Texto Longo')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('usa_lista_opcoes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=150)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='core.campoformulario')),
            ],
        ),
    ]
