# Generated by Django 6.0.3 on 2026-04-01 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Cadastro', 'verbose_name_plural': 'Cadastros'},
        ),
        migrations.AlterModelOptions(
            name='campoformulario',
            options={'ordering': ['ordem', 'rotulo'], 'verbose_name': 'Campo formulário', 'verbose_name_plural': 'Campos formulário'},
        ),
        migrations.AlterModelOptions(
            name='opcaocampo',
            options={'ordering': ['campo', 'ordem', 'valor'], 'verbose_name': 'Opção campo', 'verbose_name_plural': 'Opções campo'},
        ),
        migrations.AddField(
            model_name='cadastro',
            name='coordenada_texto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipo_coordenada',
            field=models.CharField(choices=[('decimal', 'Decimal'), ('gms', 'GMS'), ('utm', 'UTM')], default='decimal', max_length=20),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cadastros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome_cadastrador',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cadastros', to='core.cidade'),
        ),
    ]
