# Generated by Django 6.0.3 on 2026-04-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cidade_alter_cadastro_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='cidade',
        ),
        migrations.AlterModelOptions(
            name='campoformulario',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Campo do Formulário', 'verbose_name_plural': 'Campos do Formulário'},
        ),
        migrations.AlterModelOptions(
            name='opcaocampo',
            options={'ordering': ['campo', 'ordem', 'id'], 'verbose_name': 'Opção do Campo', 'verbose_name_plural': 'Opções do Campo'},
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='coordenada_texto',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='tipo_coordenada',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='campoformulario',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome_cadastrador',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='status_sincronizacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('sincronizado', 'Sincronizado'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='FotoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_cadastros/')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.cadastro')),
            ],
            options={
                'verbose_name': 'Foto do Cadastro',
                'verbose_name_plural': 'Fotos do Cadastro',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
