# Generated by Django 6.0.3 on 2026-04-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cadastro_cidade_alter_campoformulario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome', 'uf'],
            },
        ),
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-data_cadastro', '-hora_cadastro'], 'verbose_name': 'Cadastro', 'verbose_name_plural': 'Cadastros'},
        ),
        migrations.AlterModelOptions(
            name='campoformulario',
            options={'ordering': ['ordem', 'rotulo'], 'verbose_name': 'Campo formulário', 'verbose_name_plural': 'Campos formulário'},
        ),
        migrations.AlterModelOptions(
            name='opcaocampo',
            options={'ordering': ['campo', 'ordem', 'valor'], 'verbose_name': 'Opção campo', 'verbose_name_plural': 'Opções campo'},
        ),
        migrations.RemoveField(
            model_name='campoformulario',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipo_coordenada',
            field=models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual')], default='gps', max_length=20),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='status_sincronizacao',
            field=models.CharField(default='pendente', max_length=30),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cadastros', to='core.cidade'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(max_length=150)),
                ('ativo_no_app', models.BooleanField(default=True)),
                ('pode_cadastrar', models.BooleanField(default=True)),
                ('pode_sincronizar', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuário',
                'verbose_name_plural': 'Perfis de usuários',
            },
        ),
        migrations.DeleteModel(
            name='FotoCadastro',
        ),
    ]
