# Generated by Django 6.0.3 on 2026-04-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cidade_alter_cadastro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='sistema_coordenadas',
            field=models.CharField(choices=[('sirgas2000', 'SIRGAS2000')], default='sirgas2000', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin_site', 'Administrador do site'), ('cadastrador_app', 'Cadastrador do app')], default='cadastrador_app', max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='status_sincronizacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('sincronizado', 'Sincronizado'), ('erro', 'Erro')], default='pendente', max_length=30),
        ),
        migrations.CreateModel(
            name='FotoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='cadastros/fotos/')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.cadastro')),
            ],
            options={
                'verbose_name': 'Foto do cadastro',
                'verbose_name_plural': 'Fotos do cadastro',
                'ordering': ['cadastro', 'ordem'],
            },
        ),
    ]
