# Generated by Django 6.0.3 on 2026-04-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cadastro_sistema_coordenadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='fotocadastro',
            name='cadastro',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Cadastro', 'verbose_name_plural': 'Cadastros'},
        ),
        migrations.AlterModelOptions(
            name='campoformulario',
            options={'ordering': ['ordem', 'rotulo'], 'verbose_name': 'Campo do formulário', 'verbose_name_plural': 'Campos do formulário'},
        ),
        migrations.AlterModelOptions(
            name='opcaocampo',
            options={'ordering': ['campo', 'ordem', 'valor'], 'verbose_name': 'Opção do campo', 'verbose_name_plural': 'Opções do campo'},
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='sistema_coordenadas',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='tipo_coordenada',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to='cadastros/fotos/'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='cadastros/fotos/'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='cadastros/fotos/'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='foto_4',
            field=models.ImageField(blank=True, null=True, upload_to='cadastros/fotos/'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='foto_5',
            field=models.ImageField(blank=True, null=True, upload_to='cadastros/fotos/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='id_ponto',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='FotoCadastro',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
