# Generated by Django 6.0.3 on 2026-04-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cadastro_cidade_remove_fotocadastro_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='campoformulario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opcaocampo',
            options={},
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='foto_1',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='foto_2',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='foto_3',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='foto_4',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='foto_5',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='id_ponto',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='status_sincronizacao',
            field=models.CharField(default='pendente', max_length=30),
        ),
    ]
